#ifndef GLSurfDef_h
#define GLSurfDef_h

//***** MAIN SURFACES (IT IS KEPT FOR BOTH MENU AND MAIN)
#define GL_SURF_MAIN_FONT_FILENAME				"Data//Pics//MAIN_SURF_00.bmp"
#define GL_SURF_MAIN_FONT_TEXID					0

//***** MENU SURFACES
#define GL_SURF_MENU_BACKGROUND1_FILENAME		"Data//Pics//GL_SURF_01.bmp"
#define GL_SURF_MENU_BACKGROUND1_TEXID			1
#define GL_SURF_MENU_BUTTONS1_FILENAME			"Data//Pics//MENU_SURF_02.bmp"
#define GL_SURF_MENU_BUTTONS1_TEXID				2
#define GL_SURF_MENU_CURSOR_FILENAME			"Data//Pics//MENU_SURF_03.bmp"
#define GL_SURF_MENU_CURSOR_TEXID				3
#define GL_SURF_MENU_CHARACTER_FILENAME			"Data//Pics//MENU_SURF_04.bmp"
#define GL_SURF_MENU_CHARACTER_TEXID			4
#define GL_SURF_MENU_BUTTONS2_FILENAME			"Data//Pics//MENU_SURF_05.bmp"
#define GL_SURF_MENU_BUTTONS2_TEXID				5
#define GL_SURF_MENU_LIGHTS_FILENAME			"Data//Pics//MENU_SURF_06.bmp"
#define GL_SURF_MENU_LIGHTS_TEXID				6
#define GL_SURF_MENU_BUTTONS3_FILENAME			"Data//Pics//MENU_SURF_07.bmp"
#define GL_SURF_MENU_BUTTONS3_TEXID				7
#define GL_SURF_MENU_IP_FILENAME				"Data//Pics//MENU_SURF_08.bmp"
#define GL_SURF_MENU_IP_TEXID					8

//***** GAME SURFACES
#define GL_SURF_GAME_CURSOR_FILENAME			"Data//Pics//CURSOR.bmp"
#define GL_SURF_GAME_CURSOR_TEXID				9
#define GL_SURF_GAME_CHARACTER_FILENAME			"Data//Pics//GAME_SURF_10.bmp"
#define GL_SURF_GAME_CHARACTER_TEXID			10
#define GL_SURF_GAME_SWITCHER_FILENAME			"Data//Pics//SWITCHER.bmp"
#define GL_SURF_GAME_SWITCHER_TEXID				11
//#define GL_SURF_GAME_GAMEOVER_FILENAME			"Data//Pics//GAME_SURF_12.bmp"
//#define GL_SURF_GAME_GAMEOVER_TEXID				11
#define GL_SURF_GAME_YOUWIN_FILENAME			"Data//Pics//GAME_SURF_12.bmp"
#define GL_SURF_GAME_YOUWIN_TEXID				12

#define GL_SURF_MAIN_TITLE00_FILENAME			"Data//Pics//MAIN_SURF_13.bmp"
#define GL_SURF_MAIN_TITLE00_TEXID				13

#define GL_SURF_MAIN_TITLE01_FILENAME			"Data//Pics//MAIN_SURF_14.bmp"
#define GL_SURF_MAIN_TITLE01_TEXID				14

#define GL_SURF_MENU_BACKGROUND2_FILENAME		"Data//Pics//GL_SURF_02.bmp"
#define GL_SURF_MENU_BACKGROUND2_TEXID			15
#define GL_SURF_MENU_BACKGROUND3_FILENAME		"Data//Pics//GL_SURF_03.bmp"
#define GL_SURF_MENU_BACKGROUND3_TEXID			16
#define GL_SURF_MENU_BACKGROUND4_FILENAME		"Data//Pics//GL_SURF_04.bmp"
#define GL_SURF_MENU_BACKGROUND4_TEXID			17

//****SPECAIL SURF DEFINES AFTER THIS MARK ARE TEXTURES USED ONLY BY OPENGL*****
#define GL_SURF_MAIN_SYSFONT_FILENAME			"Data//Pics//tga//font.tga"
#define GL_SURF_MAIN_SYSFONT_TEXTID				20

#define GL_SURF_GAME_PARTICLE_RED_FILENAME		"Data//Pics//tga//Red.tga"
#define GL_SURF_GAME_PARTICLE_RED_TEXID			21

#define GL_SURF_GAME_PARTICLE_YELLOW_FILENAME	"Data//Pics//tga//Yellow.tga"
#define GL_SURF_GAME_PARTICLE_YELLOW_TEXID		22

#define GL_SURF_GAME_PARTICLE_GREEN_FILENAME	"Data//Pics//tga//Green.tga"
#define GL_SURF_GAME_PARTICLE_GREEN_TEXID		23

#define GL_SURF_GAME_PARTICLE_CYAN_FILENAME		"Data//Pics//tga//Cyan.tga"
#define GL_SURF_GAME_PARTICLE_CYAN_TEXID		24

#define GL_SURF_GAME_PARTICLE_PURPLE_FILENAME	"Data//Pics//tga//Purple.tga"
#define GL_SURF_GAME_PARTICLE_PURPLE_TEXID		25

#define GL_SURF_GAME_PARTICLE_BLUE_FILENAME		"Data//Pics//tga//Blue.tga"
#define GL_SURF_GAME_PARTICLE_BLUE_TEXID		26

#define	GL_SURF_GAME_BOARDER_FILENAME			"Data//Pics//GAME_SURF_100.BMP"
#define	GL_SURF_GAME_BOARDER_TEXID				27


#endif