#ifndef ModeSettings_h
#define ModeSettings_h


//*** HERE IS WHERE THE MINUTES FOR THE TIME TRIAL IS DEFINED
#define	TTRIAL_MINUTES_ALLOTED		2

//*** HERE IS WHERE THE PASSWORDS FOR THE PUZZLES ARE DEFINED
#define PUZZLE_PASSWORD_LEVEL1		"WELCOME"
#define PUZZLE_PASSWORD_LEVEL2		"IHOPEYOURNOT"
#define PUZZLE_PASSWORD_LEVEL3		"STUCKONTHESE"
#define PUZZLE_PASSWORD_LEVEL4		"LEVELS"
#define PUZZLE_PASSWORD_LEVEL5		"CUPSOFLOVIN"
#define PUZZLE_PASSWORD_LEVEL6		"CUPOFJAVA"
#define PUZZLE_PASSWORD_LEVEL7		"CUPOFCSHARP"
#define PUZZLE_PASSWORD_LEVEL8		"CUPOFMD"
#define PUZZLE_PASSWORD_LEVEL9		"THISISFORMY"
#define PUZZLE_PASSWORD_LEVEL10		"HOMMIES"
#define PUZZLE_PASSWORD_LEVEL11		"VASH"
#define PUZZLE_PASSWORD_LEVEL12		"LOVEPEACE"
#define PUZZLE_PASSWORD_LEVEL13		"DRAGONBALLZ"
#define PUZZLE_PASSWORD_LEVEL14		"KAMEHAMEHA"
#define PUZZLE_PASSWORD_LEVEL15		"KIOKENX10"
#define PUZZLE_PASSWORD_LEVEL16		"FLYINGCOWS"
#define PUZZLE_PASSWORD_LEVEL17		"RAININGFROGS"
#define PUZZLE_PASSWORD_LEVEL18		"MONKEYS"
#define PUZZLE_PASSWORD_LEVEL19		"THEMATRIX"
#define PUZZLE_PASSWORD_LEVEL20		"THEREALWORLD"
#define PUZZLE_PASSWORD_LEVEL21		"ICECREAM"
#define PUZZLE_PASSWORD_LEVEL22		"DANGERGIRL"
#define PUZZLE_PASSWORD_LEVEL23		"KNIGHT"
#define PUZZLE_PASSWORD_LEVEL24		"PHATBURGER"
#define PUZZLE_PASSWORD_LEVEL25		"INANDOUT"
#define PUZZLE_PASSWORD_LEVEL26		"JOHNWASHERE"
#define PUZZLE_PASSWORD_LEVEL27		"JACKWASHERE"
#define PUZZLE_PASSWORD_LEVEL28		"YOURMOM"
#define PUZZLE_PASSWORD_LEVEL29		"MACHOBURRITO"
#define PUZZLE_PASSWORD_LEVEL30		"MOUNTAINDUDE"
#define PUZZLE_PASSWORD_LEVEL31		"LISTENUP"
#define PUZZLE_PASSWORD_LEVEL32		"CTD"
#define PUZZLE_PASSWORD_LEVEL33		"ISASWEETGAME"
#define PUZZLE_PASSWORD_LEVEL34		"YOU"
#define PUZZLE_PASSWORD_LEVEL35		"MUST"
#define PUZZLE_PASSWORD_LEVEL36		"REALLY"
#define PUZZLE_PASSWORD_LEVEL37		"LIKE"
#define PUZZLE_PASSWORD_LEVEL38		"MATRIXATTACK"
#define PUZZLE_PASSWORD_LEVEL39		"GOAWAY"
#define PUZZLE_PASSWORD_LEVEL40		"SECRETLEVEL"
/*
#define PUZZLE_PASSWORD_LEVEL41		"PUZZLE41"
#define PUZZLE_PASSWORD_LEVEL42		"PUZZLE42"
#define PUZZLE_PASSWORD_LEVEL43		"PUZZLE43"
#define PUZZLE_PASSWORD_LEVEL44		"PUZZLE44"
#define PUZZLE_PASSWORD_LEVEL45		"PUZZLE45"
#define PUZZLE_PASSWORD_LEVEL46		"PUZZLE46"
#define PUZZLE_PASSWORD_LEVEL47		"PUZZLE47"
#define PUZZLE_PASSWORD_LEVEL48		"PUZZLE48"
#define PUZZLE_PASSWORD_LEVEL49		"PUZZLE49"
#define PUZZLE_PASSWORD_LEVEL50		"PUZZLE50"
*/

#endif